# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
