# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
