# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 16:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('kankara', 'Kankara'), ('drinks', 'Drinks'), ('card', 'Recharge Card')], max_length=15, verbose_name='Business Type')),
                ('amount_paid', models.IntegerField(default=0, verbose_name='Amount Paid')),
                ('amount_balance', models.IntegerField(default=0, verbose_name='Balance')),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(default=datetime.date(2017, 12, 27))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='customers.Customer')),
            ],
        ),
    ]
