# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('fully paid', 'Fully Paid'), ('partly paid', 'Partly Paid'), ('not paid', 'Not Paid')], default='fully paid', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='business_type',
            field=models.CharField(choices=[('kankara', 'Kankara'), ('drinks', 'Drinks'), ('card', 'Recharge Card')], max_length=120, verbose_name='Business Type'),
        ),
    ]
