# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20171227_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
