# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20171227_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('fully paid', 'Fully Paid'), ('partly paid', 'Partly Paid'), ('not paid', 'Not Paid')], default='fully paid', max_length=120),
        ),
    ]
