# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20171227_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount Paid'),
        ),
    ]
