# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20171228_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('fully paid', 'Fully Paid'), ('partly paid', 'Partly Paid'), ('not paid', 'Awiin')], max_length=120),
        ),
    ]
